# Generated by Django 3.2.4 on 2021-12-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_usersubscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='name',
            field=models.CharField(default='kjj', max_length=21),
            preserve_default=False,
        ),
    ]
