# Generated by Django 3.2.4 on 2021-12-28 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userproduct',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='userproduct',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userproduct',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
